@url = http://localhost:7071/api
#@url = https://todoapi01ms.azurewebsites.net

### Create todo 1
POST {{url}}/todos
content-type: application/json

{
    "task": "Go for a walk and talk"
}

### Create todo 2
POST {{url}}/todos
content-type: application/json

{
    "task": "Cook dinner"
}

### Create todo 3
POST {{url}}/todos
content-type: application/json

{
    "task": "Learn Python"
}

### Get all todos
GET {{url}}/todos

@id = hereGoesTheUuid
### Get todo by id 
GET {{url}}/todos/{{id}}

### Update status of todo
PUT {{url}}/todos/{{id}}
content-type: application/json

{
    "status" : "Finished"
}

### Delete todo
DELETE {{url}}/todos/{{id}}
