

@url = http://localhost:7071/api
#@url = https://todoapi01ms.azurewebsites.net

### Get all todos
GET {{url}}/todos


### Get todo by id 
GET {{url}}/todos/0b078315-ce11-4195-8236-0b3f6bea376a

### Create todo
POST {{url}}/todos
content-type: application/json

{
    "task": "Go for a walk and talk"
}

### Create todo
POST {{url}}/todos
content-type: application/json

{
    "task": "Cook dinner"
}


### Update todo (just the title)
PUT {{url}}/todos/10
content-type: application/json

{
    "title" : "Do some more work"
}

### Update todo (just done)
PUT {{url}}/todos/0b078315-ce11-4195-8236-0b3f6bea376a
content-type: application/json

{
    "Status" : "Finished"
}

### Delete todo
DELETE {{url}}/todos/0b078315-ce11-4195-8236-0b3f6bea376a